services:
  device-registry:
    build:
      context: .
      dockerfile: services/device-registry/Dockerfile
    container_name: device_registry
    environment:
      APP_PORT: 8081
      POSTGRES_DSN: ${POSTGRES_DSN}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  config-service:
    build:
      context: .
      dockerfile: services/config-service/Dockerfile
    container_name: config_service
    environment:
      APP_PORT: 8082
      POSTGRES_DSN: ${POSTGRES_DSN}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy

  mqtt-adapter:
    build:
      context: .
      dockerfile: services/mqtt-adapter/Dockerfile
    container_name: mqtt_adapter
    environment:
      APP_PORT: 8083
      POSTGRES_DSN: ${POSTGRES_DSN}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      MQTT_BROKER_URL: tcp://mosquitto:1883
      MQTT_CLIENT_ID: mqtt-adapter
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mosquitto:
        condition: service_healthy

  device-sim-1:
    build:
      context: .
      dockerfile: services/device-simulator/Dockerfile
    image: device-sim-1:latest
    container_name: device_sim_1
    environment:
      DEVICE_ID: e1445dc6-17e7-4b52-9b60-e091dee665d8
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
    depends_on:
      mosquitto:
        condition: service_healthy

  deployment-orchestrator:
    build:
      context: .
      dockerfile: services/deployment-orchestrator/Dockerfile
    container_name: deployment_orchestrator
    environment:
      APP_PORT: 8084
      POSTGRES_DSN: ${POSTGRES_DSN}
      MQTT_ADAPTER_URL: http://mqtt-adapter:8083
      ML_SERVICE_URL: http://ml-service:8086
      TWIN_SERVICE_URL: http://digital-twin-service:8087
      LWM2M_ADAPTER_URL: http://lwm2m-adapter:8088
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
      mqtt-adapter:
        condition: service_started
      lwm2m-adapter:
        condition: service_started


  telemetry-ingestor:
    build:
      context: .
      dockerfile: services/telemetry-ingestor/Dockerfile
    container_name: telemetry_ingestor
    environment:
      APP_PORT: 8085
      POSTGRES_DSN: ${POSTGRES_DSN}
      MQTT_BROKER_URL: tcp://mosquitto:1883
      MQTT_CLIENT_ID: telemetry-ingestor
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_healthy

  ml-service:
    build:
      context: .
      dockerfile: services/ml-service/Dockerfile
    container_name: ml_service
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      MODEL_DIR: /app/model_artifacts
      WINDOW_SIZE: 12
    ports:
      - "8086:8086"
    volumes:
      - ml_model_data:/app/model_artifacts
    depends_on:
      postgres:
        condition: service_healthy

  digital-twin-service:
    build:
      context: .
      dockerfile: services/digital-twin-service/Dockerfile
    container_name: digital_twin_service
    environment:
      APP_PORT: 8087
      POSTGRES_DSN: ${POSTGRES_DSN}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
    ports:
      - "8087:8087"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy


  lwm2m-adapter:
    build:
      context: .
      dockerfile: services/lwm2m-adapter/Dockerfile
    container_name: lwm2m_adapter
    environment:
      APP_PORT: 8088
      POSTGRES_DSN: ${POSTGRES_DSN}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      MQTT_BROKER_URL: tcp://mosquitto:1883
      MQTT_CLIENT_ID: lwm2m-adapter
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mosquitto:
        condition: service_healthy

  lwm2m-device-simulator:
    build:
      context: .
      dockerfile: services/lwm2m-device-simulator/Dockerfile
    image: lwm2m-device-simulator:latest

volumes:
  ml_model_data: